"""Dotmac Inbox: tenant-scoped, trait-driven conversation ownership.

The package owns durable conversation threads, messages, lifecycle, and
per-operator read cursors. Products retain contact resolution, routing,
assignment, delivery, attachments, and every transport/provider decision.
"""

from dotmac_inbox.channels import (
    AddressForm,
    ChannelSpec,
    MessageIdScope,
    ThreadIdentity,
    Transport,
    TransportMessageIdScope,
    UnknownChannelError,
    channel_spec,
    register_channels,
    registered_channels,
    reset_channel_registry_for_tests,
)
from dotmac_inbox.history import (
    ImportConversation,
    ImportMessage,
    ImportMessageTransportRef,
    ImportReadState,
    import_conversation,
    import_message,
    import_message_transport_ref,
    import_read_state,
)
from dotmac_inbox.lifecycle import (
    UNTIL_REPLY,
    Direction,
    InvalidTransitionError,
    ReasonSpec,
    SnoozeUntilReply,
    Status,
    UnknownReasonError,
    is_open,
    register_reasons,
    registered_reasons,
    reset_reason_registry_for_tests,
    validate_reason,
    validate_transition,
)
from dotmac_inbox.manifest import module
from dotmac_inbox.migrations import versions_dir
from dotmac_inbox.models import (
    SCHEMA,
    TENANT_MODELS,
    TENANT_TABLES,
    Conversation,
    ConversationReadState,
    Message,
    MessageTransportRef,
)
from dotmac_inbox.read import (
    ConversationFilter,
    ConversationPage,
    ConversationView,
    MessagePage,
    MessageView,
)
from dotmac_inbox.read_service import (
    get_conversation,
    list_conversations,
    list_messages,
)
from dotmac_inbox.service import (
    ConversationConflict,
    ConversationNotFound,
    StaleConversationState,
    bind_message_observation_ref,
    bind_message_transport_ref,
    create_conversation,
    find_message_by_transport_ref,
    mark_conversation_read,
    record_message,
    transition_conversation_status,
)
from dotmac_inbox.threading import DedupKey, InboundIdentity, dedup_key, thread_key
from dotmac_inbox.transport import TransportMessageIdentity

__version__ = "0.1.0a2+dev"

__all__ = [
    "__version__",
    "SCHEMA",
    "TENANT_MODELS",
    "TENANT_TABLES",
    "UNTIL_REPLY",
    "AddressForm",
    "ChannelSpec",
    "Conversation",
    "ConversationConflict",
    "ConversationFilter",
    "ConversationNotFound",
    "ConversationPage",
    "ConversationReadState",
    "ConversationView",
    "DedupKey",
    "Direction",
    "ImportConversation",
    "ImportMessage",
    "ImportMessageTransportRef",
    "ImportReadState",
    "InboundIdentity",
    "InvalidTransitionError",
    "Message",
    "MessageIdScope",
    "MessagePage",
    "MessageTransportRef",
    "MessageView",
    "ReasonSpec",
    "SnoozeUntilReply",
    "StaleConversationState",
    "Status",
    "ThreadIdentity",
    "Transport",
    "TransportMessageIdScope",
    "TransportMessageIdentity",
    "UnknownChannelError",
    "UnknownReasonError",
    "bind_message_observation_ref",
    "bind_message_transport_ref",
    "channel_spec",
    "create_conversation",
    "dedup_key",
    "find_message_by_transport_ref",
    "get_conversation",
    "import_conversation",
    "import_message",
    "import_message_transport_ref",
    "import_read_state",
    "is_open",
    "list_conversations",
    "list_messages",
    "mark_conversation_read",
    "module",
    "record_message",
    "register_channels",
    "register_reasons",
    "registered_channels",
    "registered_reasons",
    "reset_channel_registry_for_tests",
    "reset_reason_registry_for_tests",
    "thread_key",
    "transition_conversation_status",
    "validate_reason",
    "validate_transition",
    "versions_dir",
]
