"""Public contract for dotmac-tax."""

from dotmac_tax.contracts import (
    StatutoryReportBoxInput,
    TaxAuthorityInput,
    TaxFact,
    TaxJurisdictionInput,
    TaxRuleBandInput,
    TaxRuleInput,
)
from dotmac_tax.manifest import module
from dotmac_tax.service import (
    TaxConflict,
    TaxNotFound,
    TaxRuleViolation,
    accept_tax_return,
    amend_tax_return,
    approve_tax_return,
    create_filing_obligation,
    create_statutory_report_definition,
    create_tax_authority,
    create_tax_code,
    create_tax_jurisdiction,
    create_tax_return,
    determine_tax,
    file_tax_return,
    generate_statutory_report,
    prepare_tax_return,
    publish_tax_rule,
    reject_tax_return,
    update_tax_authority,
    update_tax_code,
    update_tax_jurisdiction,
)

__version__ = "0.1.0a1"

__all__ = [
    "StatutoryReportBoxInput",
    "TaxAuthorityInput",
    "TaxConflict",
    "TaxFact",
    "TaxJurisdictionInput",
    "TaxNotFound",
    "TaxRuleBandInput",
    "TaxRuleInput",
    "TaxRuleViolation",
    "__version__",
    "accept_tax_return",
    "amend_tax_return",
    "approve_tax_return",
    "create_filing_obligation",
    "create_statutory_report_definition",
    "create_tax_authority",
    "create_tax_code",
    "create_tax_jurisdiction",
    "create_tax_return",
    "determine_tax",
    "file_tax_return",
    "generate_statutory_report",
    "module",
    "prepare_tax_return",
    "publish_tax_rule",
    "reject_tax_return",
    "update_tax_authority",
    "update_tax_code",
    "update_tax_jurisdiction",
]
