"""Dotmac's product-neutral tenant positioning contract."""

from __future__ import annotations

from dotmac_positioning.contracts import (
    CircleFence,
    CollectionGrantInput,
    CurrentPositionSnapshot,
    GeofenceConflict,
    GeofenceEvaluationInput,
    GeofenceFactOutput,
    GeofenceShape,
    GeofenceTransition,
    ObservationDisposition,
    ObservationInput,
    ObservationOutcome,
    ObservationPolicy,
    PolygonFence,
    PositioningError,
    PositionObservationConflict,
    PositionObservationRejected,
    RecordBatchResult,
    SourceAssignmentConflict,
    SourceAssignmentInput,
    TrackedUnitNotFound,
    TrailPoint,
)
from dotmac_positioning.manifest import module
from dotmac_positioning.migrations import versions_dir
from dotmac_positioning.models import (
    SCHEMA,
    TENANT_MODELS,
    TENANT_TABLES,
    CollectionGrant,
    CurrentPosition,
    Geofence,
    GeofenceFact,
    GeofenceState,
    PositionObservation,
    SourceAssignment,
    SourceIdentity,
    TrackedUnit,
)
from dotmac_positioning.service import (
    assign_source,
    create_geofence,
    create_tracked_unit,
    deactivate_geofence,
    evaluate_geofences,
    get_current_position,
    get_trail,
    grant_collection,
    prune_observations,
    rebuild_current_position,
    record_observations,
    resolve_tracked_unit,
    revoke_collection,
    unassign_source,
)

__version__ = "0.1.0a1"

__all__ = [
    "SCHEMA",
    "TENANT_MODELS",
    "TENANT_TABLES",
    "CircleFence",
    "CollectionGrant",
    "CollectionGrantInput",
    "CurrentPosition",
    "CurrentPositionSnapshot",
    "Geofence",
    "GeofenceConflict",
    "GeofenceEvaluationInput",
    "GeofenceFact",
    "GeofenceFactOutput",
    "GeofenceShape",
    "GeofenceState",
    "GeofenceTransition",
    "ObservationDisposition",
    "ObservationInput",
    "ObservationOutcome",
    "ObservationPolicy",
    "PolygonFence",
    "PositionObservation",
    "PositionObservationConflict",
    "PositionObservationRejected",
    "PositioningError",
    "RecordBatchResult",
    "SourceAssignment",
    "SourceAssignmentConflict",
    "SourceAssignmentInput",
    "SourceIdentity",
    "TrackedUnit",
    "TrackedUnitNotFound",
    "TrailPoint",
    "__version__",
    "assign_source",
    "create_geofence",
    "create_tracked_unit",
    "deactivate_geofence",
    "evaluate_geofences",
    "get_current_position",
    "get_trail",
    "grant_collection",
    "module",
    "prune_observations",
    "rebuild_current_position",
    "record_observations",
    "resolve_tracked_unit",
    "revoke_collection",
    "unassign_source",
    "versions_dir",
]
