"""Product-neutral tenant editorial content owner."""

from dotmac_content.contracts import (
    AttachItemCreative,
    AttachPlanCreative,
    Conflict,
    ContentCreativeReferenceV1,
    ContentError,
    ContentSnapshotV1,
    ContentVariantSnapshotV1,
    CreateContentItem,
    CreateContentPlan,
    CreateContentVariant,
    NotFound,
    UpdateContentItem,
    UpdateContentPlan,
)
from dotmac_content.lifecycle import (
    ContentItemState,
    ContentPlanStatus,
    TransitionError,
    check_item_transition,
    check_plan_transition,
    validate_plan_date_range,
)
from dotmac_content.manifest import module
from dotmac_content.migrations import versions_dir
from dotmac_content.models import (
    ContentItem,
    ContentItemCreative,
    ContentPlan,
    ContentPlanCreative,
    ContentVariant,
)
from dotmac_content.service import (
    attach_item_creative,
    attach_plan_creative,
    build_content_snapshot,
    count_content_items,
    count_content_plans,
    create_content_item,
    create_content_plan,
    create_content_variant,
    get_content_item,
    get_content_plan,
    list_content_items,
    list_content_plans,
    update_content_item,
    update_content_plan,
)

__version__ = "0.1.0a1"

__all__ = [
    "AttachItemCreative",
    "AttachPlanCreative",
    "Conflict",
    "ContentCreativeReferenceV1",
    "ContentError",
    "ContentItem",
    "ContentItemCreative",
    "ContentItemState",
    "ContentPlan",
    "ContentPlanCreative",
    "ContentPlanStatus",
    "ContentSnapshotV1",
    "ContentVariant",
    "ContentVariantSnapshotV1",
    "CreateContentItem",
    "CreateContentPlan",
    "CreateContentVariant",
    "NotFound",
    "TransitionError",
    "UpdateContentItem",
    "UpdateContentPlan",
    "__version__",
    "attach_item_creative",
    "attach_plan_creative",
    "build_content_snapshot",
    "check_item_transition",
    "check_plan_transition",
    "count_content_items",
    "count_content_plans",
    "create_content_item",
    "create_content_plan",
    "create_content_variant",
    "get_content_item",
    "get_content_plan",
    "list_content_items",
    "list_content_plans",
    "module",
    "update_content_item",
    "update_content_plan",
    "validate_plan_date_range",
    "versions_dir",
]
