"""Tenant supplier-liability authority extracted product-first from ERP."""

from dotmac_payables.contracts import (
    AccountingConsequence,
    AccountingEntry,
    AccountingReceiptInput,
    ApplyCredit,
    Conflict,
    ConsequenceSource,
    CreateCreditNote,
    CreateSupplierInvoice,
    CreditNoteStatus,
    InvalidAmount,
    InvalidTransition,
    InvoiceStatus,
    NotFound,
    ObligationSchedule,
    ObligationStatus,
    PayableLineInput,
    PayablesError,
    SettlementObservationInput,
)
from dotmac_payables.manifest import module
from dotmac_payables.migrations import versions_dir
from dotmac_payables.models import (
    AccountingReceipt,
    CreditApplication,
    CreditNote,
    CreditNoteLine,
    LiabilityEvent,
    PaymentObligation,
    SettlementObservation,
    SupplierInvoice,
    SupplierInvoiceLine,
)
from dotmac_payables.service import (
    apply_credit_note,
    approve_credit_note,
    approve_invoice,
    build_credit_accounting_consequence,
    build_invoice_accounting_consequence,
    create_credit_note,
    create_invoice,
    record_accounting_receipt,
    record_settlement,
    submit_credit_note,
    submit_invoice,
    supplier_liability_balance,
    void_credit_note,
    void_invoice,
)

__version__ = "0.1.0a1"

__all__ = [
    "AccountingConsequence",
    "AccountingEntry",
    "AccountingReceipt",
    "AccountingReceiptInput",
    "ApplyCredit",
    "Conflict",
    "ConsequenceSource",
    "CreateCreditNote",
    "CreateSupplierInvoice",
    "CreditApplication",
    "CreditNote",
    "CreditNoteLine",
    "CreditNoteStatus",
    "InvalidAmount",
    "InvalidTransition",
    "InvoiceStatus",
    "LiabilityEvent",
    "NotFound",
    "ObligationSchedule",
    "ObligationStatus",
    "PayableLineInput",
    "PayablesError",
    "PaymentObligation",
    "SettlementObservation",
    "SettlementObservationInput",
    "SupplierInvoice",
    "SupplierInvoiceLine",
    "__version__",
    "apply_credit_note",
    "approve_credit_note",
    "approve_invoice",
    "build_credit_accounting_consequence",
    "build_invoice_accounting_consequence",
    "create_credit_note",
    "create_invoice",
    "module",
    "record_accounting_receipt",
    "record_settlement",
    "submit_credit_note",
    "submit_invoice",
    "supplier_liability_balance",
    "versions_dir",
    "void_credit_note",
    "void_invoice",
]
