"""Public surface of the optional ``dotmac-party`` context module."""

from dotmac_party.contracts import (
    AddContactPoint,
    AssignPartyRole,
    ContactConsentStatus,
    ContactVerificationStatus,
    CreatePartyMembership,
    MembershipStatus,
    PartyConflict,
    PartyInvariantError,
    PartyModuleError,
    PartyNotFound,
    RecordExternalReference,
    RelatePartyRoles,
    RelationshipStatus,
    RoleStatus,
)
from dotmac_party.manifest import module
from dotmac_party.migrations import versions_dir
from dotmac_party.models import (
    PartyContactPoint,
    PartyExternalReference,
    PartyMembership,
    PartyRelationship,
    PartyRole,
)
from dotmac_party.service import (
    add_contact_point,
    assign_role,
    create_membership,
    record_external_reference,
    relate_roles,
    set_contact_active,
    set_contact_consent,
    set_contact_verification,
    set_primary_contact,
    transition_membership,
    transition_relationship,
    transition_role,
)
from dotmac_party.vocabulary import (
    ContactChannelSpec,
    MembershipTypeSpec,
    PartyVocabularyError,
    PartyVocabularyRegistry,
    RelationshipTypeSpec,
    RoleTypeSpec,
    normalize_email,
    normalize_phone,
    normalize_text,
)

__version__ = "0.1.0a1"

__all__ = [
    "AddContactPoint",
    "AssignPartyRole",
    "ContactChannelSpec",
    "ContactConsentStatus",
    "ContactVerificationStatus",
    "CreatePartyMembership",
    "MembershipStatus",
    "MembershipTypeSpec",
    "PartyConflict",
    "PartyContactPoint",
    "PartyExternalReference",
    "PartyInvariantError",
    "PartyMembership",
    "PartyModuleError",
    "PartyNotFound",
    "PartyRelationship",
    "PartyRole",
    "PartyVocabularyError",
    "PartyVocabularyRegistry",
    "RecordExternalReference",
    "RelatePartyRoles",
    "RelationshipStatus",
    "RelationshipTypeSpec",
    "RoleStatus",
    "RoleTypeSpec",
    "add_contact_point",
    "assign_role",
    "create_membership",
    "module",
    "normalize_email",
    "normalize_phone",
    "normalize_text",
    "record_external_reference",
    "relate_roles",
    "set_contact_active",
    "set_contact_consent",
    "set_primary_contact",
    "set_contact_verification",
    "transition_membership",
    "transition_relationship",
    "transition_role",
    "versions_dir",
]
