"""Public contract for the reusable Dotmac durable-assets owner."""

from dotmac_assets.contracts import (
    AssetCondition,
    AssetCreate,
    AssetSnapshot,
    AssetState,
    AssignmentCreate,
    AssignmentEnd,
    AssignmentStatus,
    AssignmentTransfer,
    DisposalApprove,
    DisposalCancel,
    DisposalComplete,
    DisposalMethod,
    DisposalRequest,
    DisposalStatus,
    MaintenanceCancel,
    MaintenanceComplete,
    MaintenanceKind,
    MaintenanceSchedule,
    MaintenanceStatus,
)
from dotmac_assets.lifecycle import (
    AssetLifecycleError,
    InvalidTransition,
    SeparationOfDutiesViolation,
    StaleState,
    transition_asset,
    transition_assignment,
    transition_disposal,
    transition_maintenance,
)
from dotmac_assets.manifest import module
from dotmac_assets.migrations import versions_dir
from dotmac_assets.service import (
    AssetConflict,
    AssetNotFound,
    approve_disposal,
    assign_asset,
    cancel_disposal,
    cancel_maintenance,
    complete_disposal,
    complete_maintenance,
    create_asset,
    create_asset_snapshot,
    end_assignment,
    move_asset,
    request_disposal,
    schedule_maintenance,
    start_maintenance,
    transfer_asset,
    transition_asset_state,
)

__version__ = "0.1.0a1"

__all__ = [
    "__version__",
    "AssetCondition",
    "AssetConflict",
    "AssetCreate",
    "AssetLifecycleError",
    "AssetNotFound",
    "AssetState",
    "AssetSnapshot",
    "AssignmentCreate",
    "AssignmentEnd",
    "AssignmentStatus",
    "AssignmentTransfer",
    "DisposalApprove",
    "DisposalCancel",
    "DisposalComplete",
    "DisposalMethod",
    "DisposalRequest",
    "DisposalStatus",
    "InvalidTransition",
    "MaintenanceCancel",
    "MaintenanceComplete",
    "MaintenanceKind",
    "MaintenanceSchedule",
    "MaintenanceStatus",
    "SeparationOfDutiesViolation",
    "StaleState",
    "approve_disposal",
    "assign_asset",
    "cancel_disposal",
    "cancel_maintenance",
    "complete_disposal",
    "complete_maintenance",
    "create_asset",
    "create_asset_snapshot",
    "end_assignment",
    "module",
    "move_asset",
    "request_disposal",
    "schedule_maintenance",
    "start_maintenance",
    "transfer_asset",
    "transition_asset",
    "transition_asset_state",
    "transition_assignment",
    "transition_disposal",
    "transition_maintenance",
    "versions_dir",
]
