"""Public surface for the controlled-documents owner."""

from dotmac_documents.contracts import (
    AccessEffect,
    AccessPrincipal,
    AccessTarget,
    AcknowledgeVersion,
    AddAnnotation,
    AddRendition,
    AddVersion,
    ApprovalVerdict,
    CheckoutConflict,
    CreateDocument,
    CreateDocumentTypeVersion,
    CreateLibrary,
    DocumentAccessDecision,
    DocumentError,
    DocumentNotFound,
    DocumentState,
    DocumentTimerRequest,
    FileEvidence,
    GrantDocumentAccess,
    InvalidLifecycleTransition,
    MetadataInvalid,
    RelationKind,
    RenditionKind,
    ScheduleDocumentTransition,
    SourceProvenance,
    VersionBump,
    VersionConflict,
)
from dotmac_documents.manifest import module
from dotmac_documents.migrations import versions_dir
from dotmac_documents.service import (
    acknowledge_version,
    acquire_checkout,
    add_annotation,
    add_rendition,
    add_version,
    classify_document,
    create_document,
    create_document_type_version,
    create_library,
    decide_document_access,
    grant_document_access,
    relate_documents,
    release_checkout,
    renew_checkout,
    resolve_annotation,
    schedule_document_transition,
    transition_document,
)

__version__ = "0.1.0a1"

__all__ = [
    "AccessEffect",
    "AccessPrincipal",
    "AccessTarget",
    "AcknowledgeVersion",
    "AddAnnotation",
    "AddRendition",
    "AddVersion",
    "ApprovalVerdict",
    "CheckoutConflict",
    "CreateDocument",
    "CreateDocumentTypeVersion",
    "CreateLibrary",
    "DocumentError",
    "DocumentAccessDecision",
    "DocumentNotFound",
    "DocumentState",
    "DocumentTimerRequest",
    "FileEvidence",
    "GrantDocumentAccess",
    "InvalidLifecycleTransition",
    "MetadataInvalid",
    "RelationKind",
    "RenditionKind",
    "ScheduleDocumentTransition",
    "SourceProvenance",
    "VersionBump",
    "VersionConflict",
    "__version__",
    "acknowledge_version",
    "acquire_checkout",
    "add_annotation",
    "add_rendition",
    "add_version",
    "classify_document",
    "create_document",
    "create_document_type_version",
    "create_library",
    "decide_document_access",
    "grant_document_access",
    "module",
    "relate_documents",
    "release_checkout",
    "renew_checkout",
    "resolve_annotation",
    "schedule_document_transition",
    "transition_document",
    "versions_dir",
]
