"""Poetry is one pinned build input, not a workstation preference.

The same repository previously used three incompatible truths at once:
``poetry.lock`` and CI were generated/run with Poetry 2.4.1, while the
production Dockerfile installed 1.8.3 and a developer could run any Poetry on
``PATH``.  That makes lock drift version-dependent and lets a container prove a
different dependency graph from CI.

``[tool.poetry].requires-poetry`` is the owner.  Bootstrap locks, the lockfile
generator, CI, Docker and local gates must all agree with it exactly.
"""

from __future__ import annotations

import tomllib
from pathlib import Path

import pytest

from scripts.check_poetry_toolchain import (
    PoetryToolchainError,
    active_version,
    bootstrap_version,
    lock_generator_version,
    require_match,
    required_version,
)

REPO = Path(__file__).resolve().parents[2]
PYPROJECT = REPO / "pyproject.toml"
LOCK = REPO / "poetry.lock"
BOOTSTRAP = REPO / ".github" / "bootstrap"
ACTION = REPO / ".github" / "actions" / "setup-poetry" / "action.yml"
DOCKERFILE = REPO / "Dockerfile"
DOCKERIGNORE = REPO / ".dockerignore"
MAKEFILE = REPO / "Makefile"
WORKFLOWS = REPO / ".github" / "workflows"


def test_every_poetry_surface_uses_the_project_pin() -> None:
    wanted = required_version(PYPROJECT.read_text(encoding="utf-8"))
    assert wanted == lock_generator_version(LOCK.read_text(encoding="utf-8"))

    locks = sorted(BOOTSTRAP.glob("poetry-requirements-py*.txt"))
    assert locks, "the Poetry bootstrap has no hash-locked requirements"
    for lock in locks:
        assert bootstrap_version(lock.read_text(encoding="utf-8")) == wanted


@pytest.mark.parametrize(
    ("reader", "bad", "reason"),
    [
        (
            required_version,
            '[tool.poetry]\nrequires-poetry = ">=2.4"\n',
            "a range lets different Poetry versions rewrite one lock",
        ),
        (
            lock_generator_version,
            "# generated by something else\n",
            "a missing generator stamp makes the comparison vacuous",
        ),
        (
            bootstrap_version,
            "poetry==2.4.1\npoetry==2.3.1\n",
            "two Poetry requirements do not define one installer",
        ),
    ],
)
def test_ambiguous_or_missing_versions_fail_closed(
    reader, bad: str, reason: str
) -> None:
    with pytest.raises(PoetryToolchainError):
        reader(bad)


def test_version_mismatch_is_observable_before_a_poetry_command_runs() -> None:
    assert active_version("Poetry (version 2.4.1)") == "2.4.1"
    with pytest.raises(PoetryToolchainError, match="active Poetry uses Poetry 2.3.1"):
        require_match("2.4.1", "2.3.1", "active Poetry")
    with pytest.raises(PoetryToolchainError, match="unexpected output"):
        active_version("Poetry is somewhere on PATH")


def test_ci_and_docker_verify_the_pin_on_both_sides_of_install() -> None:
    action = ACTION.read_text(encoding="utf-8")
    dockerfile = DOCKERFILE.read_text(encoding="utf-8")
    dockerignore = DOCKERIGNORE.read_text(encoding="utf-8")

    assert action.count("scripts/check_poetry_toolchain.py") >= 2
    assert "--active" in action
    assert "ARG POETRY_VERSION" not in dockerfile
    assert "poetry-requirements-py312.txt" in dockerfile
    assert "!.github/bootstrap/" in dockerignore
    assert "!.github/bootstrap/poetry-requirements-py312.txt" in dockerignore
    assert "--require-hashes" in dockerfile
    assert dockerfile.count("scripts/check_poetry_toolchain.py") >= 2
    assert "--active" in dockerfile


def test_every_workflow_that_executes_poetry_uses_the_pinned_setup() -> None:
    offenders: list[str] = []
    for path in sorted([*WORKFLOWS.glob("*.yml"), *WORKFLOWS.glob("*.yaml")]):
        body = path.read_text(encoding="utf-8")
        executable_poetry = any(
            "run:" in line and "poetry" in line.lower() for line in body.splitlines()
        ) or any(line.lstrip().startswith("poetry ") for line in body.splitlines())
        if executable_poetry and "uses: ./.github/actions/setup-poetry" not in body:
            offenders.append(path.name)
    assert not offenders, (
        "workflows execute an ambient Poetry instead of the pinned bootstrap: "
        f"{offenders}"
    )


def test_make_check_validates_the_committed_lock_without_regenerating_it() -> None:
    makefile = MAKEFILE.read_text(encoding="utf-8")
    assert "poetry-lock-check:" in makefile
    recipe = makefile.split("poetry-lock-check:", 1)[1].split("\n\n", 1)[0]
    assert "check_poetry_toolchain.py --active" in recipe
    assert "poetry check --lock" in recipe
    assert "poetry lock" not in recipe.replace("poetry check --lock", "")


def test_the_real_project_pin_is_exact_not_a_range() -> None:
    poetry = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))["tool"]["poetry"]
    assert poetry["requires-poetry"] == required_version(PYPROJECT.read_text())
