"""Public surface of the reusable Dotmac Orders owner."""

from dotmac_orders.contracts import (
    AcceptOrderCommand,
    AcknowledgeFulfillmentCommand,
    ActorRef,
    CancelOrderCommand,
    CoverageResolutionV1,
    CoverageSnapshotV1,
    FulfillmentRequestV1,
    FxSnapshotV1,
    LineInput,
    LineSnapshot,
    OrderCommandResult,
    OrderEventV1,
    OrderLineSnapshotV1,
    OrderSnapshotV1,
    OrderTotals,
    ReconciliationReport,
    RecordCoverageResolutionCommand,
    SubmitOrderCommand,
    TaxSnapshotV1,
    TermsSnapshotV1,
    TermValueV1,
)
from dotmac_orders.engine import (
    DEFAULT_ORDER_STATES,
    OrderPhase,
    OrderStateRegistry,
    OrderStateSpec,
    calculate_line_snapshot,
    calculate_order_totals,
    default_order_state_registry,
    snapshot_fingerprint,
)
from dotmac_orders.errors import OrderConflict, OrderError, OrderNotFound
from dotmac_orders.manifest import module
from dotmac_orders.migrations import versions_dir
from dotmac_orders.service import (
    accept_order,
    acknowledge_fulfillment,
    cancel_order,
    get_order_snapshot,
    get_order_timeline,
    reconcile_fulfillment_publications,
    record_coverage_resolution,
    submit_order,
)

__version__ = "0.1.0a1"

__all__ = [
    "DEFAULT_ORDER_STATES",
    "AcceptOrderCommand",
    "AcknowledgeFulfillmentCommand",
    "ActorRef",
    "CancelOrderCommand",
    "CoverageResolutionV1",
    "CoverageSnapshotV1",
    "FulfillmentRequestV1",
    "FxSnapshotV1",
    "LineInput",
    "LineSnapshot",
    "OrderCommandResult",
    "OrderEventV1",
    "OrderConflict",
    "OrderError",
    "OrderLineSnapshotV1",
    "OrderNotFound",
    "OrderPhase",
    "OrderSnapshotV1",
    "OrderStateRegistry",
    "OrderStateSpec",
    "OrderTotals",
    "ReconciliationReport",
    "RecordCoverageResolutionCommand",
    "SubmitOrderCommand",
    "TaxSnapshotV1",
    "TermValueV1",
    "TermsSnapshotV1",
    "accept_order",
    "acknowledge_fulfillment",
    "calculate_line_snapshot",
    "calculate_order_totals",
    "cancel_order",
    "default_order_state_registry",
    "get_order_snapshot",
    "get_order_timeline",
    "module",
    "reconcile_fulfillment_publications",
    "record_coverage_resolution",
    "snapshot_fingerprint",
    "submit_order",
    "versions_dir",
]
