"""Approved managed-suite dataflow, without runtime values or providers."""

from .catalogue import (
    CAPABILITY_COMPOSITIONS,
    CAPABILITY_CONTRACTS,
    CAPABILITY_SCHEMAS,
    COLLABORATION_FEDERATION,
    COMPOSITION_DEPENDENCY_CONTRACTS,
    COMPOSITION_DEPENDENCY_SCHEMAS,
    EMAIL_APPLICATION_DEPENDENCIES,
    EMAIL_DNS,
    EMAIL_FEDERATION,
    IDENTITY_ACCOUNT_FEDERATION,
    IDENTITY_FEDERATION,
    PRODUCT_MANIFEST,
)

__version__ = "0.1.0a1"

__all__ = [
    "CAPABILITY_COMPOSITIONS",
    "CAPABILITY_CONTRACTS",
    "CAPABILITY_SCHEMAS",
    "COLLABORATION_FEDERATION",
    "COMPOSITION_DEPENDENCY_CONTRACTS",
    "COMPOSITION_DEPENDENCY_SCHEMAS",
    "EMAIL_APPLICATION_DEPENDENCIES",
    "EMAIL_DNS",
    "EMAIL_FEDERATION",
    "IDENTITY_FEDERATION",
    "IDENTITY_ACCOUNT_FEDERATION",
    "PRODUCT_MANIFEST",
    "__version__",
]
