"""Pinned GitHub metadata observation; no live fetch occurs on a runner."""

from __future__ import annotations

from dotmac_runner_transport import ExactHost, ProviderDomainSnapshotV1

__all__ = ["DOMAIN_NAMES", "SNAPSHOT"]

DOMAIN_NAMES = (
    "api.github.com",
    "broker.actions.githubusercontent.com",
    "cafe.github.com",
    "codeload.github.com",
    "containers.pkg.github.com",
    "docker-proxy.pkg.github.com",
    "docker.pkg.github.com",
    "ghcr.io",
    "github-registry-files.githubusercontent.com",
    "github-releases.githubusercontent.com",
    "github.com",
    "hosted-compute-request-orchestrator-prod-eus-01.githubapp.com",
    "hosted-compute-request-orchestrator-prod-eus-02.githubapp.com",
    "hosted-compute-request-orchestrator-prod-iad-01.githubapp.com",
    "hosted-compute-request-orchestrator-prod-iad-02.githubapp.com",
    "launch.actions.githubusercontent.com",
    "maven.pkg.github.com",
    "mpsghub.actions.githubusercontent.com",
    "npm-beta-proxy.pkg.github.com",
    "npm-beta.pkg.github.com",
    "npm-proxy.pkg.github.com",
    "npm.pkg.github.com",
    "nuget.pkg.github.com",
    "objects-origin.githubusercontent.com",
    "objects.githubusercontent.com",
    "pipelinesghubeus1.actions.githubusercontent.com",
    "pipelinesghubeus10.actions.githubusercontent.com",
    "pipelinesghubeus11.actions.githubusercontent.com",
    "pipelinesghubeus12.actions.githubusercontent.com",
    "pipelinesghubeus13.actions.githubusercontent.com",
    "pipelinesghubeus14.actions.githubusercontent.com",
    "pipelinesghubeus15.actions.githubusercontent.com",
    "pipelinesghubeus2.actions.githubusercontent.com",
    "pipelinesghubeus20.actions.githubusercontent.com",
    "pipelinesghubeus21.actions.githubusercontent.com",
    "pipelinesghubeus22.actions.githubusercontent.com",
    "pipelinesghubeus23.actions.githubusercontent.com",
    "pipelinesghubeus24.actions.githubusercontent.com",
    "pipelinesghubeus25.actions.githubusercontent.com",
    "pipelinesghubeus26.actions.githubusercontent.com",
    "pipelinesghubeus3.actions.githubusercontent.com",
    "pipelinesghubeus4.actions.githubusercontent.com",
    "pipelinesghubeus5.actions.githubusercontent.com",
    "pipelinesghubeus6.actions.githubusercontent.com",
    "pipelinesghubeus7.actions.githubusercontent.com",
    "pipelinesghubeus8.actions.githubusercontent.com",
    "pipelinesghubeus9.actions.githubusercontent.com",
    "pipelinesproxcnc1.actions.githubusercontent.com",
    "pipelinesproxcus1.actions.githubusercontent.com",
    "pipelinesproxeau1.actions.githubusercontent.com",
    "pipelinesproxjpw1.actions.githubusercontent.com",
    "pipelinesproxsdc1.actions.githubusercontent.com",
    "pipelinesproxweu1.actions.githubusercontent.com",
    "pipelinesproxwus31.actions.githubusercontent.com",
    "pipelinesproxwus32.actions.githubusercontent.com",
    "pkg.actions.githubusercontent.com",
    "productionresultssa0.blob.core.windows.net",
    "productionresultssa1.blob.core.windows.net",
    "productionresultssa10.blob.core.windows.net",
    "productionresultssa11.blob.core.windows.net",
    "productionresultssa12.blob.core.windows.net",
    "productionresultssa13.blob.core.windows.net",
    "productionresultssa14.blob.core.windows.net",
    "productionresultssa15.blob.core.windows.net",
    "productionresultssa16.blob.core.windows.net",
    "productionresultssa17.blob.core.windows.net",
    "productionresultssa18.blob.core.windows.net",
    "productionresultssa19.blob.core.windows.net",
    "productionresultssa2.blob.core.windows.net",
    "productionresultssa3.blob.core.windows.net",
    "productionresultssa4.blob.core.windows.net",
    "productionresultssa5.blob.core.windows.net",
    "productionresultssa6.blob.core.windows.net",
    "productionresultssa7.blob.core.windows.net",
    "productionresultssa8.blob.core.windows.net",
    "productionresultssa9.blob.core.windows.net",
    "pypi.pkg.github.com",
    "release-assets.githubusercontent.com",
    "results-receiver.actions.githubusercontent.com",
    "rubygems.pkg.github.com",
    "run-actions-1-azure-eastus.actions.githubusercontent.com",
    "run-actions-2-azure-eastus.actions.githubusercontent.com",
    "run-actions-3-azure-eastus.actions.githubusercontent.com",
    "runner-auth.actions.githubusercontent.com",
    "runnerghubeus1.actions.githubusercontent.com",
    "runnerghubeus20.actions.githubusercontent.com",
    "runnerghubeus21.actions.githubusercontent.com",
    "runnerghubwus31.actions.githubusercontent.com",
    "runnerproxcnc1.actions.githubusercontent.com",
    "runnerproxcus1.actions.githubusercontent.com",
    "runnerproxeau1.actions.githubusercontent.com",
    "runnerproxjpw1.actions.githubusercontent.com",
    "runnerproxsdc1.actions.githubusercontent.com",
    "runnerproxweu1.actions.githubusercontent.com",
    "setup-tools.actions.githubusercontent.com",
    "swift.pkg.github.com",
    "tokenghub.actions.githubusercontent.com",
    "vstoken.actions.githubusercontent.com",
)

SNAPSHOT = ProviderDomainSnapshotV1(
    source_uri="https://api.github.com/meta",
    observed_at="2026-08-31T10:25:13Z",
    semantic_sha256="sha256:5b627613a4626e103869d44fb0be3ec320daba3d107eefab543b0a60e3bd0492",
    field="domains.actions_inbound.full_domains",
    domains=tuple(ExactHost(name) for name in DOMAIN_NAMES),
)
