"""Closed managed host contracts, never a remote execution facility."""

from .catalogue import (
    BACKUP_RESTORE_LIFECYCLE,
    CAPABILITY_COMPOSITIONS,
    CAPABILITY_CONTRACTS,
    CAPABILITY_SCHEMAS,
    COMPOSITION_DEPENDENCY_CONTRACTS,
    COMPOSITION_DEPENDENCY_SCHEMAS,
    DEPLOYMENT_BUNDLE_LIFECYCLE,
    HEALTH_PROBE_LIFECYCLE,
    PRODUCT_MANIFEST,
)

__version__ = "0.1.0a1"

__all__ = [
    "BACKUP_RESTORE_LIFECYCLE",
    "CAPABILITY_COMPOSITIONS",
    "CAPABILITY_CONTRACTS",
    "CAPABILITY_SCHEMAS",
    "COMPOSITION_DEPENDENCY_CONTRACTS",
    "COMPOSITION_DEPENDENCY_SCHEMAS",
    "DEPLOYMENT_BUNDLE_LIFECYCLE",
    "HEALTH_PROBE_LIFECYCLE",
    "PRODUCT_MANIFEST",
    "__version__",
]
