"""``dotmac-deployment-foundation`` — one build-and-deploy facility for the fleet.

A product assembly declares `deploy/product.toml` and nothing else. Everything a
deployment needs is rendered or derived from it: the Compose file, the ingress
site, the collector configuration, the alert rules, and the ordered deployment
plan with its gates.

Read ADR-0070 for the boundary and `EXTRACTION.toml` for what was extracted from
which product and, as importantly, what was deliberately left behind.

## Three properties this package holds on purpose

**Zero runtime dependencies.** Not the kernel, not SQLAlchemy, not FastAPI, not
Jinja, not a YAML library. Standard library only — the same shape as
`dotmac-ui`, for the same reason: a build runner that renders a Compose file has
no database and no web framework, and must not acquire them to validate a
descriptor.

**No state.** No `ModuleManifest`, no models, no migrations, no lineage, no
tenant. A facility that decides how a deployment is built cannot be a table
inside one of the deployments it builds.

**Nothing here runs anything.** The plan is data and the executor talks to an
injected `Effects` provider. That is what makes the failure-injection matrix —
wrong digest, failed backup, candidate never ready, maintenance-required
release attempted online — ordinary unit tests instead of disposable-VM
exercises, and a gate that has never been shown to fire is a gate nobody should
trust.
"""

from __future__ import annotations

from .ancestry import (
    PERMITTED_ORDERINGS,
    DowngradeOverride,
    Ordering,
    ReleaseOrdering,
    refuse_backwards_deploy,
)
from .application_profile import (
    ApplicationFoundationProfile,
    ConcernBinding,
    FoundationConcern,
    InapplicableConcern,
    WriterClaim,
)
from .authorization import OPERATIONS, ExecutionGrant, authorize
from .backup import (
    ArtefactClass,
    Assurance,
    BackupHealth,
    BackupRecord,
    assess,
    restore_rehearsal,
    retention_keep,
)
from .canonical_plan import canonical_plan_bytes
from .conformance import check_all, check_rendered_assets_match
from .database_drift import (
    POSTGRES_SYSTEM_EXCLUSIONS,
    DatabaseContractDriftReport,
    DatabaseContractGap,
    DatabaseContractGapCode,
    DatabaseDriftClassification,
    DatabaseDriftExclusions,
    DatabaseDriftFinding,
    DatabaseDriftPhase,
    DatabaseFactDimension,
    DatabaseFactDirection,
    EffectivePrivilegeAuditUniverse,
    EffectivePrivilegeExclusion,
    EffectivePrivilegeKey,
    NameExclusion,
    ObservedDatabaseState,
    PrefixExclusion,
    PrivilegeUniverseDerivation,
    compare_database_contract,
)
from .database_structure import (
    DATABASE_CATALOG_COMPARATOR_CONTRACT,
    DATABASE_CATALOG_FACT_SCOPE,
    DATABASE_DESCRIPTOR_CATALOG_BINDING_SCHEMA,
    MODULE_DATABASE_CATALOG_SCHEMA,
    POSTGRES_TABLES_COLUMNS_OBSERVATION_SCHEMA,
    PRODUCT_DATABASE_CATALOG_SCHEMA,
    DatabaseCatalogCoordinateV1,
    DatabaseCatalogProductIdentityV1,
    DatabaseCatalogScope,
    DatabaseDescriptorCatalogBindingV1,
    DatabaseStructureComparisonResultV1,
    DatabaseStructureCoverageV1,
    DatabaseStructureFactAttribute,
    DatabaseStructureFactKeyV1,
    DatabaseStructureFindingV1,
    DatabaseStructureObservationEvidenceV1,
    DatabaseStructureVerifierComparisonV1,
    DatabaseStructureVerifierDriftV1,
    DatabaseStructureVerifierV1,
    DatabaseStructureWitnessV1,
    StructureFactDimension,
    StructureFactDirection,
    accept_database_structure_comparison,
)
from .digest import ALGORITHMS, CANONICAL_ALGORITHM, Digest, require_same_digest
from .document import (
    DESCRIPTOR_DOCUMENT_SCHEMA,
    DeploymentDescriptorDocumentV1,
    build_canonical_document,
)
from .drift import DriftReport, Observation, Verdict, compare
from .engine import (
    DeploymentOutcome,
    DeploymentPlan,
    Effects,
    Executor,
    Step,
    StepKind,
    Strategy,
    build_plan,
    deployment_lock,
    format_plan,
    steps_for_rollback,
)
from .errors import (
    DeploymentError,
    DeploymentFoundationError,
    DriftDetected,
    LockUnavailableError,
    PreconditionFailed,
    RenderDrift,
    SecretValueError,
    SpecError,
    StepFailed,
    UnknownFieldError,
    UnknownSchemaError,
)
from .evidence import (
    RELEASE_EVIDENCE_SCHEMA,
    ReleaseEvidenceV1,
    SignatureVerifier,
    TrustPolicy,
    accept_release_evidence,
)
from .execution_plan import (
    EXECUTION_PLAN_DIGEST_SCHEMA,
    EXECUTION_PLAN_SCHEMA,
    FoundationExecutionPlanV1,
    canonical_execution_plan_bytes,
    execution_plan_digest,
    render_execution_plan,
    require_execution_plan_digest,
)
from .exposure import (
    OWNERSHIP_PREFIX,
    ExposureEffects,
    ExposureTransaction,
    Finding,
    HostObservation,
    PrivilegedVantageError,
    ProbeOutcome,
    ProbeResult,
    ProbeVantage,
    Severity,
    VerificationReport,
    accept_public_exposure_evidence,
    apply_exposure,
    foreign_rules,
    observation_from_text,
    ownership_comment,
    verify_exposure,
)
from .external_recovery import (
    EXTERNAL_RECEIPT_SCHEMA,
    VERIFICATION_EVIDENCE,
    ExternalRecoveryReceiptV1,
    accept_external_recovery_receipt,
    backup_record_from_receipt,
    require_restore_proof,
)
from .image import AuditReport, audit_image
from .ingress import (
    ADDRESS_FAMILIES,
    EXPOSURES,
    INGRESS_POLICY_SCHEMA,
    PROVIDERS,
    EdgeEndpoint,
    FirewallRule,
    ProviderCapability,
    admit_bind_address,
    endpoint_token,
)
from .launcher import (
    LauncherIdentity,
    identify_launcher,
    refuse_untrusted_launcher,
)
from .lease import (
    DEFAULT_LEASE_DIR,
    HOST_LEASE_SCHEMA,
    HostLease,
    load_lease,
    write_lease,
)
from .policy import (
    build_edge_plan,
    build_firewall_plan,
    ingress_policy_document,
    public_endpoint_tokens,
)
from .provenance import (
    PROVENANCE_SCHEMA,
    AuthorizationReceipt,
    DeploymentProvenanceV1,
    build_provenance,
    normalize_digest,
)
from .recovery import (
    COMPONENTS,
    RECOVERY_BUNDLE_SCHEMA,
    RECOVERY_RECEIPT_SCHEMA,
    RESTORE_PROCEDURE,
    Adjudication,
    BundleComponent,
    CatalogEvidence,
    Disposition,
    EffectivePrivilegeFact,
    FunctionSecurityFact,
    InvariantBreach,
    MembershipFact,
    RecoveryBundleManifestV1,
    RecoveryNotProved,
    RecoveryReceiptV1,
    RestoreAttempt,
    RestoreStep,
    RoleClosure,
    RoleFact,
    adjudicate_restore,
    build_manifest,
    build_recovery_receipt,
    classify_invariant_breaches,
    derive_role_closure,
    invariant_breaches,
    load_manifest,
    refuse_identity_stripping,
    restore_plan,
    verify_plane_isolation,
    verify_recovery,
)
from .recovery_execution import (
    RecoveryEffects,
    RecoveryExecutor,
    RecoveryOutcome,
    RecoverySession,
    RestoreTarget,
)
from .recovery_identity import (
    EXECUTOR_KINDS,
    PRIVILEGE_VERIFICATIONS,
    DatasetIdentityV1,
    ExternalExecutorV1,
)
from .recovery_plan import (
    RECOVERY_PLAN_DIGEST_SCHEMA,
    RECOVERY_PLAN_SCHEMA,
    CapturedPrestateV1,
    DesiredPoststateV1,
    FailedSystemObservationV1,
    RecoveryExecutionPlanV1,
    canonical_recovery_plan_bytes,
    recovery_plan_digest,
    render_recovery_plan,
    require_recovery_plan_digest,
)
from .rehearsal import (
    REHEARSAL_RECEIPT_SCHEMA,
    REQUIRED_ITEMS,
    LaneThreeItem,
    RehearsalReceiptV1,
    RequirementResult,
    RequirementStatus,
    build_receipt,
    render_status_document,
    verify_publication,
)
from .spec import (
    SCHEMA,
    SCHEMA_V1,
    SCHEMA_V2,
    SCHEMAS,
    DatabaseContract,
    DatabaseRole,
    IsolationInvariant,
    ProductDeploymentSpec,
)
from .telemetry import (
    RESOURCE_ATTRIBUTES,
    Annotation,
    ResourceAttributes,
    resource_attributes,
)
from .transition import (
    DATABASE_TRANSITION_RECEIPT_SCHEMA,
    DATABASE_TRANSITION_SCHEMA,
    PROMOTION_PENDING_SCHEMA,
    DatabaseCheckpointV1,
    DatabaseDurability,
    DatabasePostconditionV1,
    DatabasePreconditionV1,
    DatabaseTransitionAuthorizationV1,
    DatabaseTransitionGrant,
    DatabaseTransitionReceiptV1,
    DatabaseTransitionV1,
    DescriptorPromoter,
    DescriptorPromotionEvidenceV1,
    PromotionPendingV1,
    authorize_database_transition,
    observe_database_postcondition,
    promote_database_descriptor,
    recover_database_promotion,
    require_database_precondition,
)
from .vantage import (
    PRIVATE_RANGES,
    TUNNEL_KINDS,
    VantageQualification,
    qualify_vantage,
)
from .version import VERSION as __version__

__all__ = [
    "ADDRESS_FAMILIES",
    "ALGORITHMS",
    "Adjudication",
    "Annotation",
    "ArtefactClass",
    "Assurance",
    "AuditReport",
    "AuthorizationReceipt",
    "BackupHealth",
    "BackupRecord",
    "BundleComponent",
    "CANONICAL_ALGORITHM",
    "COMPONENTS",
    "CatalogEvidence",
    "DATABASE_CATALOG_COMPARATOR_CONTRACT",
    "DATABASE_CATALOG_FACT_SCOPE",
    "DATABASE_DESCRIPTOR_CATALOG_BINDING_SCHEMA",
    "DATABASE_TRANSITION_RECEIPT_SCHEMA",
    "DATABASE_TRANSITION_SCHEMA",
    "DEFAULT_LEASE_DIR",
    "DESCRIPTOR_DOCUMENT_SCHEMA",
    "DatabaseCatalogCoordinateV1",
    "DatabaseCatalogProductIdentityV1",
    "DatabaseCatalogScope",
    "DatabaseCheckpointV1",
    "DatabaseContract",
    "DatabaseContractDriftReport",
    "DatabaseContractGap",
    "DatabaseContractGapCode",
    "DatabaseDescriptorCatalogBindingV1",
    "DatabaseDriftClassification",
    "DatabaseDriftExclusions",
    "DatabaseDriftFinding",
    "DatabaseDriftPhase",
    "DatabaseDurability",
    "DatabaseFactDimension",
    "DatabaseFactDirection",
    "DatabasePostconditionV1",
    "DatabasePreconditionV1",
    "DatabaseRole",
    "DatabaseStructureComparisonResultV1",
    "DatabaseStructureCoverageV1",
    "DatabaseStructureFactAttribute",
    "DatabaseStructureFactKeyV1",
    "DatabaseStructureFindingV1",
    "DatabaseStructureObservationEvidenceV1",
    "DatabaseStructureVerifierComparisonV1",
    "DatabaseStructureVerifierDriftV1",
    "DatabaseStructureVerifierV1",
    "DatabaseStructureWitnessV1",
    "DatabaseTransitionAuthorizationV1",
    "DatabaseTransitionGrant",
    "DatabaseTransitionReceiptV1",
    "DatabaseTransitionV1",
    "DatasetIdentityV1",
    "DeploymentDescriptorDocumentV1",
    "DeploymentError",
    "DeploymentFoundationError",
    "DeploymentOutcome",
    "DeploymentPlan",
    "DeploymentProvenanceV1",
    "DescriptorPromoter",
    "DescriptorPromotionEvidenceV1",
    "Digest",
    "Disposition",
    "DowngradeOverride",
    "DriftDetected",
    "DriftReport",
    "EXECUTION_PLAN_DIGEST_SCHEMA",
    "EXECUTION_PLAN_SCHEMA",
    "EXECUTOR_KINDS",
    "EXPOSURES",
    "EXTERNAL_RECEIPT_SCHEMA",
    "EdgeEndpoint",
    "EffectivePrivilegeAuditUniverse",
    "EffectivePrivilegeExclusion",
    "EffectivePrivilegeFact",
    "EffectivePrivilegeKey",
    "Effects",
    "ApplicationFoundationProfile",
    "ConcernBinding",
    "FoundationConcern",
    "InapplicableConcern",
    "WriterClaim",
    "ExecutionGrant",
    "Executor",
    "ExposureEffects",
    "ExposureTransaction",
    "ExternalExecutorV1",
    "ExternalRecoveryReceiptV1",
    "Finding",
    "FirewallRule",
    "FoundationExecutionPlanV1",
    "FunctionSecurityFact",
    "HOST_LEASE_SCHEMA",
    "HostLease",
    "HostObservation",
    "INGRESS_POLICY_SCHEMA",
    "InvariantBreach",
    "IsolationInvariant",
    "LaneThreeItem",
    "LauncherIdentity",
    "LockUnavailableError",
    "MODULE_DATABASE_CATALOG_SCHEMA",
    "MembershipFact",
    "NameExclusion",
    "OPERATIONS",
    "RECOVERY_PLAN_DIGEST_SCHEMA",
    "RECOVERY_PLAN_SCHEMA",
    "CapturedPrestateV1",
    "DesiredPoststateV1",
    "FailedSystemObservationV1",
    "RecoveryExecutionPlanV1",
    "canonical_plan_bytes",
    "canonical_recovery_plan_bytes",
    "recovery_plan_digest",
    "render_recovery_plan",
    "require_recovery_plan_digest",
    "OWNERSHIP_PREFIX",
    "Observation",
    "ObservedDatabaseState",
    "Ordering",
    "PERMITTED_ORDERINGS",
    "POSTGRES_SYSTEM_EXCLUSIONS",
    "POSTGRES_TABLES_COLUMNS_OBSERVATION_SCHEMA",
    "PRIVATE_RANGES",
    "PRIVILEGE_VERIFICATIONS",
    "PRODUCT_DATABASE_CATALOG_SCHEMA",
    "PROMOTION_PENDING_SCHEMA",
    "PROVENANCE_SCHEMA",
    "PROVIDERS",
    "PreconditionFailed",
    "PrefixExclusion",
    "PrivilegeUniverseDerivation",
    "PrivilegedVantageError",
    "ProbeOutcome",
    "ProbeResult",
    "ProbeVantage",
    "ProductDeploymentSpec",
    "PromotionPendingV1",
    "ProviderCapability",
    "RECOVERY_BUNDLE_SCHEMA",
    "RECOVERY_RECEIPT_SCHEMA",
    "REHEARSAL_RECEIPT_SCHEMA",
    "RELEASE_EVIDENCE_SCHEMA",
    "REQUIRED_ITEMS",
    "RESOURCE_ATTRIBUTES",
    "RESTORE_PROCEDURE",
    "RecoveryEffects",
    "RecoveryExecutor",
    "RecoveryOutcome",
    "RecoverySession",
    "RestoreTarget",
    "RecoveryBundleManifestV1",
    "RecoveryNotProved",
    "RecoveryReceiptV1",
    "RehearsalReceiptV1",
    "ReleaseEvidenceV1",
    "ReleaseOrdering",
    "RenderDrift",
    "RequirementResult",
    "RequirementStatus",
    "ResourceAttributes",
    "RestoreAttempt",
    "RestoreStep",
    "RoleClosure",
    "RoleFact",
    "SCHEMA",
    "SCHEMAS",
    "SCHEMA_V1",
    "SCHEMA_V2",
    "SecretValueError",
    "Severity",
    "SignatureVerifier",
    "SpecError",
    "Step",
    "StepFailed",
    "StepKind",
    "Strategy",
    "StructureFactDimension",
    "StructureFactDirection",
    "TUNNEL_KINDS",
    "TrustPolicy",
    "UnknownFieldError",
    "UnknownSchemaError",
    "VERIFICATION_EVIDENCE",
    "VantageQualification",
    "Verdict",
    "VerificationReport",
    "__version__",
    "accept_database_structure_comparison",
    "accept_external_recovery_receipt",
    "accept_public_exposure_evidence",
    "accept_release_evidence",
    "adjudicate_restore",
    "admit_bind_address",
    "apply_exposure",
    "assess",
    "audit_image",
    "authorize",
    "authorize_database_transition",
    "backup_record_from_receipt",
    "build_canonical_document",
    "build_edge_plan",
    "build_firewall_plan",
    "build_manifest",
    "build_plan",
    "build_provenance",
    "build_receipt",
    "build_recovery_receipt",
    "canonical_execution_plan_bytes",
    "check_all",
    "check_rendered_assets_match",
    "classify_invariant_breaches",
    "compare",
    "compare_database_contract",
    "deployment_lock",
    "derive_role_closure",
    "endpoint_token",
    "execution_plan_digest",
    "foreign_rules",
    "format_plan",
    "identify_launcher",
    "ingress_policy_document",
    "invariant_breaches",
    "load_lease",
    "load_manifest",
    "normalize_digest",
    "observation_from_text",
    "observe_database_postcondition",
    "ownership_comment",
    "promote_database_descriptor",
    "public_endpoint_tokens",
    "qualify_vantage",
    "recover_database_promotion",
    "refuse_backwards_deploy",
    "refuse_identity_stripping",
    "refuse_untrusted_launcher",
    "render_execution_plan",
    "render_status_document",
    "require_database_precondition",
    "require_execution_plan_digest",
    "require_restore_proof",
    "require_same_digest",
    "resource_attributes",
    "restore_plan",
    "restore_rehearsal",
    "retention_keep",
    "steps_for_rollback",
    "verify_exposure",
    "verify_plane_isolation",
    "verify_publication",
    "verify_recovery",
    "write_lease",
]
