"""Public surface for managed records."""

from dotmac_records.contracts import (
    ApprovalVerdict,
    CutoffRule,
    DeclareRecord,
    DefineRecordSeriesVersion,
    DefineRetentionScheduleVersion,
    DeletionAuthorization,
    DispositionBlocked,
    DispositionEvaluation,
    DispositionOutcome,
    FileSnapshot,
    FinalAction,
    HoldCaseDefinition,
    HoldTargetDefinition,
    PhysicalDeletionConfirmation,
    RecordConflict,
    RecordNotFound,
    RecordsError,
    SourceSnapshot,
    TimerRequest,
    TriggerConflict,
    TriggerObservation,
    TriggerResult,
)
from dotmac_records.manifest import module
from dotmac_records.migrations import versions_dir
from dotmac_records.service import (
    approve_disposition_batch,
    authorize_destruction,
    confirm_destruction,
    create_disposition_batch,
    declare_record,
    define_record_series_version,
    define_retention_schedule_version,
    evaluate_disposition,
    observe_retention_trigger,
    open_hold_case,
    place_hold,
    record_custody_transfer,
    record_preservation_check,
    release_hold_target,
)

__version__ = "0.1.0a1"

__all__ = [
    "ApprovalVerdict",
    "CutoffRule",
    "DeclareRecord",
    "DefineRecordSeriesVersion",
    "DefineRetentionScheduleVersion",
    "DeletionAuthorization",
    "DispositionBlocked",
    "DispositionEvaluation",
    "DispositionOutcome",
    "FileSnapshot",
    "FinalAction",
    "HoldCaseDefinition",
    "HoldTargetDefinition",
    "PhysicalDeletionConfirmation",
    "RecordConflict",
    "RecordNotFound",
    "RecordsError",
    "SourceSnapshot",
    "TimerRequest",
    "TriggerConflict",
    "TriggerObservation",
    "TriggerResult",
    "__version__",
    "approve_disposition_batch",
    "authorize_destruction",
    "confirm_destruction",
    "create_disposition_batch",
    "declare_record",
    "define_record_series_version",
    "define_retention_schedule_version",
    "evaluate_disposition",
    "module",
    "observe_retention_trigger",
    "open_hold_case",
    "place_hold",
    "record_custody_transfer",
    "record_preservation_check",
    "release_hold_target",
    "versions_dir",
]
