"""Managed collaboration lifecycle contracts, never a provider implementation."""

from .catalogue import (
    APPLICATION_LIFECYCLE,
    CAPABILITY_COMPOSITIONS,
    CAPABILITY_CONTRACTS,
    CAPABILITY_SCHEMAS,
    COMPOSITION_DEPENDENCY_CONTRACTS,
    COMPOSITION_DEPENDENCY_SCHEMAS,
    FILE_ROUNDTRIP_LIFECYCLE,
    PRODUCT_MANIFEST,
    USER_GROUP_QUOTA_LIFECYCLE,
    USER_OIDC_CONFIGURATION_LIFECYCLE,
)

__version__ = "0.1.0a1"

__all__ = [
    "APPLICATION_LIFECYCLE",
    "CAPABILITY_COMPOSITIONS",
    "CAPABILITY_CONTRACTS",
    "CAPABILITY_SCHEMAS",
    "COMPOSITION_DEPENDENCY_CONTRACTS",
    "COMPOSITION_DEPENDENCY_SCHEMAS",
    "FILE_ROUNDTRIP_LIFECYCLE",
    "PRODUCT_MANIFEST",
    "USER_GROUP_QUOTA_LIFECYCLE",
    "USER_OIDC_CONFIGURATION_LIFECYCLE",
    "__version__",
]
