"""Published surface of the reusable Dotmac subscriptions module."""

from dotmac_subscriptions.cadence import (
    BillingCadence,
    CadenceAlignment,
    CollectionTiming,
    EndOfMonthRule,
    Interval,
    IntervalUnit,
    ProrationPolicy,
    RateBasis,
    invoice_period,
    period_containing,
    proration_factor,
    rate_units_in,
    service_period,
)
from dotmac_subscriptions.commands import (
    ContractLineInput,
    ContractVersionResult,
    DurableTimerPort,
    EndContractVersionCommand,
    EndContractVersionResult,
    GenerateRecurringChargeCommand,
    OccurrenceResult,
    OfferPriceInput,
    PublishOfferVersionCommand,
    PublishOfferVersionResult,
    RecordSubscriptionContractVersionCommand,
    TimerCancelResult,
    TimerScheduleResult,
    WithdrawOfferVersionCommand,
)
from dotmac_subscriptions.contracts import (
    CommercialEntitlementProjectionV1,
    EntitlementIntent,
    EntitlementProjectionPublisher,
    FakeEntitlementProjectionPublisher,
    FakeRatedObligationPublisher,
    RatedObligationOutputV1,
    RatedObligationPublisher,
    StageResult,
)
from dotmac_subscriptions.engine import (
    FIXED_RATING_POLICY_VERSION,
    RatingInput,
    RatingResult,
    rate_recurring_line,
)
from dotmac_subscriptions.errors import (
    CadenceError,
    SubscriptionConflictError,
    SubscriptionDataError,
    SubscriptionError,
    SubscriptionStateError,
)
from dotmac_subscriptions.lifecycle import (
    ContractVersionState,
    OccurrenceState,
    OfferState,
    require_contract_transition,
    require_occurrence_transition,
    require_offer_transition,
)
from dotmac_subscriptions.linking import (
    link_platform_contract_subject,
    link_platform_offer_subject,
    link_tenant_contract_subject,
    link_tenant_offer_subject,
)
from dotmac_subscriptions.manifest import module
from dotmac_subscriptions.migrations import versions_dir
from dotmac_subscriptions.service import (
    OfferCatalogItem,
    OfferCatalogPage,
    OfferCatalogPrice,
    OfferVersionSnapshot,
    acknowledge_output,
    cadence_of,
    effective_version_at,
    end_contract_version,
    entitlement_projections_for_version,
    generate_recurring_charge,
    list_effective_offers,
    occurrences_for_contract,
    offer_version_snapshot,
    publish_offer_version,
    record_contract_version,
    unacknowledged_outputs,
    withdraw_offer_version,
)
from dotmac_subscriptions.values import (
    ExactAmount,
    canonical_decimal,
    canonical_instant,
    entitlement_projection_fingerprint,
    occurrence_idempotency_key,
    rating_input_fingerprint,
)
from dotmac_subscriptions.vocabulary import SubscriptionVocabularyRegistry

__version__ = "0.1.0a2"

__all__ = [
    "BillingCadence",
    "CadenceAlignment",
    "CadenceError",
    "CollectionTiming",
    "CommercialEntitlementProjectionV1",
    "ContractLineInput",
    "ContractVersionResult",
    "ContractVersionState",
    "DurableTimerPort",
    "EndContractVersionCommand",
    "EndContractVersionResult",
    "EndOfMonthRule",
    "EntitlementIntent",
    "EntitlementProjectionPublisher",
    "ExactAmount",
    "FakeEntitlementProjectionPublisher",
    "FakeRatedObligationPublisher",
    "FIXED_RATING_POLICY_VERSION",
    "GenerateRecurringChargeCommand",
    "Interval",
    "IntervalUnit",
    "OccurrenceResult",
    "OccurrenceState",
    "OfferPriceInput",
    "OfferState",
    "OfferCatalogItem",
    "OfferCatalogPage",
    "OfferCatalogPrice",
    "OfferVersionSnapshot",
    "ProrationPolicy",
    "PublishOfferVersionCommand",
    "PublishOfferVersionResult",
    "RateBasis",
    "RatedObligationOutputV1",
    "RatedObligationPublisher",
    "RatingInput",
    "RatingResult",
    "RecordSubscriptionContractVersionCommand",
    "StageResult",
    "SubscriptionConflictError",
    "SubscriptionDataError",
    "SubscriptionError",
    "SubscriptionStateError",
    "SubscriptionVocabularyRegistry",
    "TimerCancelResult",
    "TimerScheduleResult",
    "WithdrawOfferVersionCommand",
    "__version__",
    "acknowledge_output",
    "cadence_of",
    "canonical_decimal",
    "canonical_instant",
    "effective_version_at",
    "end_contract_version",
    "entitlement_projections_for_version",
    "entitlement_projection_fingerprint",
    "generate_recurring_charge",
    "list_effective_offers",
    "invoice_period",
    "link_platform_contract_subject",
    "link_platform_offer_subject",
    "link_tenant_contract_subject",
    "link_tenant_offer_subject",
    "module",
    "occurrence_idempotency_key",
    "occurrences_for_contract",
    "offer_version_snapshot",
    "period_containing",
    "proration_factor",
    "publish_offer_version",
    "rate_recurring_line",
    "rate_units_in",
    "rating_input_fingerprint",
    "record_contract_version",
    "require_contract_transition",
    "require_occurrence_transition",
    "require_offer_transition",
    "service_period",
    "unacknowledged_outputs",
    "withdraw_offer_version",
    "versions_dir",
]
