"""Public contract for the reusable Dotmac fulfillment owner."""

from dotmac_fulfillment.contracts import (
    AttemptRequest,
    CompensationCommand,
    CompensationDisposition,
    CompensationOutcome,
    CompensationRecord,
    CompensationRequest,
    FulfillmentConflict,
    FulfillmentError,
    FulfillmentNotFound,
    OutcomeClass,
    OutcomeMessage,
    OutcomeRecord,
    ParticipantCommand,
    ReobservationSchedule,
    RepairAction,
    RepairActor,
    RepairAttention,
    RunCreate,
    RunProgress,
    RunProgressSnapshot,
    StaleOutcome,
    StepDefinition,
)
from dotmac_fulfillment.manifest import module
from dotmac_fulfillment.migrations import versions_dir
from dotmac_fulfillment.participants import (
    DuplicateParticipantError,
    ParticipantRegistry,
    UndeclaredParticipantError,
)
from dotmac_fulfillment.service import (
    create_run,
    derive_run_progress,
    list_repair_attention,
    record_compensation_outcome,
    record_outcome,
    record_reviewed_terminal_outcome,
    request_attempt,
    request_compensation,
    request_redrive,
)

__version__ = "0.1.0a1"

__all__ = [
    "AttemptRequest",
    "CompensationCommand",
    "CompensationDisposition",
    "CompensationOutcome",
    "CompensationRecord",
    "CompensationRequest",
    "DuplicateParticipantError",
    "FulfillmentConflict",
    "FulfillmentError",
    "FulfillmentNotFound",
    "OutcomeClass",
    "OutcomeMessage",
    "OutcomeRecord",
    "ParticipantCommand",
    "ParticipantRegistry",
    "ReobservationSchedule",
    "RepairAction",
    "RepairActor",
    "RepairAttention",
    "RunCreate",
    "RunProgress",
    "RunProgressSnapshot",
    "StaleOutcome",
    "StepDefinition",
    "UndeclaredParticipantError",
    "__version__",
    "create_run",
    "derive_run_progress",
    "list_repair_attention",
    "module",
    "record_compensation_outcome",
    "record_outcome",
    "record_reviewed_terminal_outcome",
    "request_attempt",
    "request_compensation",
    "request_redrive",
    "versions_dir",
]
