"""Public surface for tenant-scoped physical work execution."""

from dotmac_work_orders.lifecycle import (
    TERMINAL_STATUSES,
    Event,
    InvalidTransition,
    Status,
    TransitionDecision,
    decide_transition,
)
from dotmac_work_orders.manifest import module
from dotmac_work_orders.migrations import versions_dir
from dotmac_work_orders.models import (
    SCHEMA,
    TENANT_TABLES,
    WorkOrder,
    WorkOrderAssignment,
    WorkOrderEvent,
    WorkOrderEvidence,
    WorkOrderNote,
    WorkOrderWorkLog,
)
from dotmac_work_orders.schemas import (
    AddEvidence,
    AddNote,
    AssignWorkOrder,
    CreateWorkOrder,
    ExecutionEvent,
    RecordWorkLog,
    UnassignWorkOrder,
    UpdateWorkOrder,
)
from dotmac_work_orders.service import (
    AssignmentRefused,
    CommandConflict,
    CompletionBlocked,
    ExecutionOutcome,
    OpenWorkLogConflict,
    UpdateRefused,
    WorkLogOverlap,
    WorkOrderError,
    WorkOrderNotFound,
    add_evidence,
    add_note,
    apply_execution_event,
    assign_work_order,
    create_work_order,
    record_worklog,
    unassign_work_order,
    update_work_order,
)

__version__ = "0.1.0a1"

__all__ = [
    "SCHEMA",
    "TENANT_TABLES",
    "TERMINAL_STATUSES",
    "AddEvidence",
    "AddNote",
    "AssignWorkOrder",
    "AssignmentRefused",
    "CommandConflict",
    "CompletionBlocked",
    "CreateWorkOrder",
    "Event",
    "ExecutionEvent",
    "ExecutionOutcome",
    "InvalidTransition",
    "OpenWorkLogConflict",
    "RecordWorkLog",
    "Status",
    "TransitionDecision",
    "WorkLogOverlap",
    "UnassignWorkOrder",
    "UpdateRefused",
    "UpdateWorkOrder",
    "WorkOrder",
    "WorkOrderAssignment",
    "WorkOrderError",
    "WorkOrderEvidence",
    "WorkOrderEvent",
    "WorkOrderNotFound",
    "WorkOrderNote",
    "WorkOrderWorkLog",
    "__version__",
    "add_evidence",
    "add_note",
    "apply_execution_event",
    "assign_work_order",
    "create_work_order",
    "decide_transition",
    "module",
    "record_worklog",
    "unassign_work_order",
    "update_work_order",
    "versions_dir",
]
