"""Managed infrastructure contracts, never a provider implementation."""

from .catalogue import (
    CAPABILITY_COMPOSITIONS,
    CAPABILITY_CONTRACTS,
    CAPABILITY_SCHEMAS,
    COMPOSITION_DEPENDENCY_CONTRACTS,
    COMPOSITION_DEPENDENCY_SCHEMAS,
    FIREWALL_LIFECYCLE,
    INSTANCE_LIFECYCLE,
    NETWORK_LIFECYCLE,
    PRODUCT_MANIFEST,
    VOLUME_LIFECYCLE,
)

__version__ = "0.1.0a1"

__all__ = [
    "CAPABILITY_COMPOSITIONS",
    "CAPABILITY_CONTRACTS",
    "CAPABILITY_SCHEMAS",
    "COMPOSITION_DEPENDENCY_CONTRACTS",
    "COMPOSITION_DEPENDENCY_SCHEMAS",
    "FIREWALL_LIFECYCLE",
    "INSTANCE_LIFECYCLE",
    "NETWORK_LIFECYCLE",
    "PRODUCT_MANIFEST",
    "VOLUME_LIFECYCLE",
    "__version__",
]
