"""Public contract for the reusable tenant-only IPAM owner."""

from dotmac_ipam.contracts import (
    AddressAssigned,
    AddressFamily,
    AddressLookup,
    AddressReserved,
    AddressSnapshot,
    AddressSpaceSnapshot,
    AddressState,
    AssignAddress,
    AssignmentLookup,
    AssignmentReleased,
    AssignmentRepaired,
    AssignmentSnapshot,
    AssignmentState,
    CreateAddressSpace,
    CreatePool,
    IPAddress,
    IPNetwork,
    PoolSnapshot,
    RecordUtilization,
    ReleaseAssignment,
    RepairAssignment,
    RepairReport,
    ReserveAddress,
    UtilizationQuery,
    UtilizationSnapshot,
)
from dotmac_ipam.manifest import module
from dotmac_ipam.migrations import versions_dir
from dotmac_ipam.service import (
    IpamConflict,
    IpamError,
    IpamNotFound,
    PoolExhausted,
    assign_address,
    create_address_space,
    create_pool,
    lookup_address,
    lookup_assignments,
    lookup_utilization,
    record_utilization,
    release_assignment,
    repair_assignment,
    reserve_address,
)

__version__ = "0.1.0a1"

__all__ = [
    "__version__",
    "AddressAssigned",
    "AddressFamily",
    "AddressLookup",
    "AddressReserved",
    "AddressSnapshot",
    "AddressSpaceSnapshot",
    "AddressState",
    "AssignAddress",
    "AssignmentLookup",
    "AssignmentReleased",
    "AssignmentRepaired",
    "AssignmentSnapshot",
    "AssignmentState",
    "CreateAddressSpace",
    "CreatePool",
    "IPAddress",
    "IPNetwork",
    "IpamConflict",
    "IpamError",
    "IpamNotFound",
    "PoolExhausted",
    "PoolSnapshot",
    "RecordUtilization",
    "ReleaseAssignment",
    "RepairAssignment",
    "RepairReport",
    "ReserveAddress",
    "UtilizationQuery",
    "UtilizationSnapshot",
    "assign_address",
    "create_address_space",
    "create_pool",
    "lookup_address",
    "lookup_assignments",
    "lookup_utilization",
    "module",
    "record_utilization",
    "release_assignment",
    "repair_assignment",
    "reserve_address",
    "versions_dir",
]
