#!/usr/bin/env python3
"""Enforce one exact Poetry version across every build surface.

The source of truth is ``[tool.poetry].requires-poetry``. This script uses only
the standard library so it can reject the wrong Poetry before any dependency
or development environment has been installed.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import NoReturn

REPO = Path(__file__).resolve().parents[1]
PYPROJECT = REPO / "pyproject.toml"
LOCK = REPO / "poetry.lock"
BOOTSTRAP = REPO / ".github" / "bootstrap"

_EXACT_VERSION = re.compile(r"[0-9]+(?:\.[0-9]+){2}(?:[A-Za-z0-9.-]+)?")
_LOCK_GENERATOR = re.compile(
    r"^# This file is automatically @generated by Poetry ([^ ]+) "
    r"and should not be changed by hand\.$"
)
_BOOTSTRAP_POETRY = re.compile(r"^poetry==([^\s\\]+)(?:\s+\\)?$", re.MULTILINE)
_ACTIVE_POETRY = re.compile(r"^Poetry \(version ([^)]+)\)$")


class PoetryToolchainError(ValueError):
    """The repository does not describe one unambiguous Poetry toolchain."""


def _fail(message: str) -> NoReturn:
    raise PoetryToolchainError(message)


def required_version(pyproject: str) -> str:
    """Return the one exact version owned by ``pyproject.toml``."""
    try:
        value = tomllib.loads(pyproject)["tool"]["poetry"]["requires-poetry"]
    except (KeyError, tomllib.TOMLDecodeError):
        _fail("pyproject.toml must declare [tool.poetry].requires-poetry")
    if not isinstance(value, str) or _EXACT_VERSION.fullmatch(value) is None:
        _fail(
            "[tool.poetry].requires-poetry must be one exact X.Y.Z version, "
            f"not {value!r}"
        )
    return value


def lock_generator_version(lockfile: str) -> str:
    """Return Poetry's generator version from the committed lock header."""
    lines = lockfile.splitlines()
    first_line = lines[0] if lines else ""
    match = _LOCK_GENERATOR.fullmatch(first_line)
    if match is None:
        _fail("poetry.lock has no recognised Poetry generator header")
    return match.group(1)


def bootstrap_version(requirements: str) -> str:
    """Return the sole Poetry pin in one hash-locked bootstrap file."""
    versions = _BOOTSTRAP_POETRY.findall(requirements)
    if len(versions) != 1:
        _fail(
            "a Poetry bootstrap requirements file must contain exactly one "
            f"poetry== pin; found {versions!r}"
        )
    return versions[0]


def active_version(output: str) -> str:
    """Parse the deliberately narrow output of ``poetry --version``."""
    match = _ACTIVE_POETRY.fullmatch(output.strip())
    if match is None:
        _fail(f"unexpected output from `poetry --version`: {output.strip()!r}")
    return match.group(1)


def require_match(wanted: str, actual: str, surface: str) -> None:
    """Reject version drift with the owning and derived surfaces named."""
    if actual != wanted:
        _fail(
            f"{surface} uses Poetry {actual}, but pyproject.toml requires " f"{wanted}"
        )


def validate_repository(bootstrap_paths: list[Path] | None = None) -> str:
    """Assert every generated/install surface agrees with the project pin."""
    wanted = required_version(PYPROJECT.read_text(encoding="utf-8"))
    actual_lock = lock_generator_version(LOCK.read_text(encoding="utf-8"))
    require_match(wanted, actual_lock, "poetry.lock")

    paths = bootstrap_paths
    if paths is None:
        paths = sorted(BOOTSTRAP.glob("poetry-requirements-py*.txt"))
    if not paths:
        _fail("no hash-locked Poetry bootstrap requirements were found")
    for path in paths:
        actual = bootstrap_version(path.read_text(encoding="utf-8"))
        require_match(wanted, actual, str(path))
    return wanted


def assert_active_version(wanted: str) -> None:
    """Fail before lock/build commands when PATH resolves to another Poetry."""
    try:
        result = subprocess.run(
            ["poetry", "--version"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError) as exc:
        _fail(f"cannot execute the required Poetry {wanted}: {exc}")
    actual = active_version(result.stdout)
    require_match(wanted, actual, "active Poetry")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--active",
        action="store_true",
        help="also require `poetry --version` to equal the project pin",
    )
    parser.add_argument(
        "--bootstrap",
        action="append",
        type=Path,
        help="validate only this bootstrap requirements file (repeatable)",
    )
    outputs = parser.add_mutually_exclusive_group()
    outputs.add_argument("--print-version", action="store_true")
    outputs.add_argument("--print-requirement", action="store_true")
    return parser


def main() -> int:
    args = _parser().parse_args()
    if args.print_version or args.print_requirement:
        wanted = required_version(PYPROJECT.read_text(encoding="utf-8"))
        print(f"poetry=={wanted}" if args.print_requirement else wanted)
        return 0

    wanted = validate_repository(args.bootstrap)
    if args.active:
        assert_active_version(wanted)
    print(f"Poetry toolchain contract holds at {wanted}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except PoetryToolchainError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
