"""Regenerate `signatures.json` from the fixture bodies and the TEST keys.

Run from the repository root::

    python tests/fixtures/meta_whatsapp/regenerate.py

Every signature is HMAC-SHA256 over the **exact bytes of the file on disk** —
not over a re-serialised document. That is the whole point of the corpus: if
someone reformats a fixture, prettifies it, or normalises its line endings, the
recorded signature stops matching and
``tests/unit/test_meta_whatsapp_ingress_conformance.py`` fails loudly instead of
the corpus quietly ceasing to prove anything.

The keys live in ``manifest.json`` and are test material by construction — the
string ``NOT-A-SECRET`` is part of every one of them. A real Meta app secret
must never appear in this repository.

This script writes evidence. It is not connector code, it performs no I/O
against any provider, and it makes no decision about what a payload means.
"""

from __future__ import annotations

import hashlib
import hmac
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def sign(body: bytes, key: str) -> str:
    """The exact header value Meta sends: ``sha256=`` + lowercase hex digest."""
    return "sha256=" + hmac.new(key.encode("utf-8"), body, hashlib.sha256).hexdigest()


def main() -> int:
    manifest = json.loads((HERE / "manifest.json").read_text(encoding="utf-8"))
    keys = manifest["signing_keys"]
    entries: dict[str, dict[str, object]] = {}

    for fixture in manifest["fixtures"]:
        relative = fixture["file"]
        body = (HERE / relative).read_bytes()
        entries[relative] = {
            "byte_length": len(body),
            "body_sha256": hashlib.sha256(body).hexdigest(),
            "signatures": {
                "primary": sign(body, keys["primary"]),
                "previous": sign(body, keys["previous"]),
                "retired": sign(body, keys["retired"]),
            },
        }

    generated = {
        "schema_version": 1,
        "_notice": (
            "GENERATED by tests/fixtures/meta_whatsapp/regenerate.py. Do not "
            "hand-edit. Signatures are over the exact bytes of each body file."
        ),
        "algorithm": "HMAC-SHA256",
        "header": manifest["signature_header"]["name"],
        "bodies": entries,
    }
    (HERE / "signatures.json").write_text(
        json.dumps(generated, indent=2, sort_keys=False) + "\n", encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
