"""Managed identity lifecycle contracts, never a provider implementation."""

from .catalogue import (
    CAPABILITY_COMPOSITIONS,
    CAPABILITY_CONTRACTS,
    CAPABILITY_SCHEMAS,
    COMPOSITION_DEPENDENCY_CONTRACTS,
    COMPOSITION_DEPENDENCY_SCHEMAS,
    OIDC_CLIENT_LIFECYCLE,
    PRODUCT_MANIFEST,
    REALM_LIFECYCLE,
    USER_LIFECYCLE,
)

__version__ = "0.1.0a1"

__all__ = [
    "CAPABILITY_COMPOSITIONS",
    "CAPABILITY_CONTRACTS",
    "CAPABILITY_SCHEMAS",
    "COMPOSITION_DEPENDENCY_CONTRACTS",
    "COMPOSITION_DEPENDENCY_SCHEMAS",
    "OIDC_CLIENT_LIFECYCLE",
    "PRODUCT_MANIFEST",
    "REALM_LIFECYCLE",
    "USER_LIFECYCLE",
    "__version__",
]
