"""Public surface for the optional DotMac imports module."""

from dotmac_imports.contracts import (
    DEFAULT_MAX_ROWS,
    MAX_SAFE_ERROR_MESSAGE,
    ColumnMapping,
    FieldDeclarationError,
    FieldSet,
    FieldSpec,
    ImportIssue,
    ImportRunNotFound,
    ImportsError,
    InvalidRunState,
    MalformedSource,
    Preview,
    PromotionRefused,
    RowApplier,
    RowRejected,
    RowStatus,
    RowValidator,
    RunProgress,
    RunStatus,
    SourceDocument,
    SourceLayout,
    SourceMismatch,
    UnmappedRequiredField,
    normalize_column,
)
from dotmac_imports.manifest import module
from dotmac_imports.models import ImportRun, ImportRunRow
from dotmac_imports.service import (
    DEFAULT_CHUNK_SIZE,
    apply_next_chunk,
    create_dry_run,
    get_run,
    mark_failed,
    promote,
    validate_next_chunk,
)
from dotmac_imports.tabular import (
    PREVIEW_ROWS,
    apply_mapping,
    auto_map,
    decode,
    decode_csv,
    mapped_rows,
    preview,
)

__version__ = "0.1.0a1"

__all__ = [
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_MAX_ROWS",
    "MAX_SAFE_ERROR_MESSAGE",
    "PREVIEW_ROWS",
    "ColumnMapping",
    "FieldDeclarationError",
    "FieldSet",
    "FieldSpec",
    "ImportRun",
    "ImportRunNotFound",
    "ImportIssue",
    "ImportRunRow",
    "ImportsError",
    "InvalidRunState",
    "MalformedSource",
    "Preview",
    "PromotionRefused",
    "RowApplier",
    "RowRejected",
    "RowStatus",
    "RowValidator",
    "RunProgress",
    "RunStatus",
    "SourceDocument",
    "SourceLayout",
    "SourceMismatch",
    "UnmappedRequiredField",
    "__version__",
    "apply_mapping",
    "apply_next_chunk",
    "auto_map",
    "create_dry_run",
    "decode",
    "decode_csv",
    "get_run",
    "mapped_rows",
    "mark_failed",
    "module",
    "normalize_column",
    "preview",
    "promote",
    "validate_next_chunk",
]
