"""Public surface for the optional DotMac imports module."""

from dotmac_imports.contracts import (
    DEFAULT_MAX_ROWS,
    MAX_SAFE_ERROR_MESSAGE,
    ColumnMapping,
    FieldDeclarationError,
    FieldSet,
    FieldSpec,
    ImportIssue,
    ImportRunNotFound,
    ImportsError,
    InvalidRunState,
    MalformedSource,
    Preview,
    PromotionRefused,
    RowApplier,
    RowRejected,
    RowStatus,
    RowValidator,
    RunProgress,
    RunStatus,
    SourceDocument,
    SourceLayout,
    SourceMismatch,
    UnmappedRequiredField,
    normalize_column,
)
from dotmac_imports.manifest import module
from dotmac_imports.migrations import versions_dir
from dotmac_imports.models import ImportPartition, ImportRun, ImportRunRow
from dotmac_imports.partitioning import (
    DEFAULT_LEASE_SECONDS,
    DEFAULT_PARTITION_BYTES,
    DEFAULT_PARTITION_ROWS,
    PartitionClaim,
    PartitionClaimLost,
    PartitionDescriptor,
    PartitionError,
    PartitionPayload,
    PartitionPlanInvalid,
    PartitionProgress,
    apply_claimed_partition,
    claim_partition,
    finalize_partitioned_run,
    iter_csv_partitions,
    register_partition_plan,
    validate_claimed_partition,
)
from dotmac_imports.service import (
    DEFAULT_CHUNK_SIZE,
    apply_next_chunk,
    create_dry_run,
    get_run,
    mark_failed,
    promote,
    validate_next_chunk,
)
from dotmac_imports.tabular import (
    PREVIEW_ROWS,
    apply_mapping,
    auto_map,
    decode,
    decode_csv,
    mapped_rows,
    preview,
)

__version__ = "0.1.0a2"

__all__ = [
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_LEASE_SECONDS",
    "DEFAULT_MAX_ROWS",
    "DEFAULT_PARTITION_BYTES",
    "DEFAULT_PARTITION_ROWS",
    "MAX_SAFE_ERROR_MESSAGE",
    "PREVIEW_ROWS",
    "ColumnMapping",
    "FieldDeclarationError",
    "FieldSet",
    "FieldSpec",
    "ImportRun",
    "ImportRunNotFound",
    "ImportIssue",
    "ImportPartition",
    "ImportRunRow",
    "ImportsError",
    "InvalidRunState",
    "MalformedSource",
    "PartitionClaim",
    "PartitionClaimLost",
    "PartitionDescriptor",
    "PartitionError",
    "PartitionPayload",
    "PartitionPlanInvalid",
    "PartitionProgress",
    "Preview",
    "PromotionRefused",
    "RowApplier",
    "RowRejected",
    "RowStatus",
    "RowValidator",
    "RunProgress",
    "RunStatus",
    "SourceDocument",
    "SourceLayout",
    "SourceMismatch",
    "UnmappedRequiredField",
    "__version__",
    "apply_mapping",
    "apply_claimed_partition",
    "apply_next_chunk",
    "auto_map",
    "claim_partition",
    "create_dry_run",
    "decode",
    "decode_csv",
    "get_run",
    "finalize_partitioned_run",
    "iter_csv_partitions",
    "mapped_rows",
    "mark_failed",
    "module",
    "normalize_column",
    "preview",
    "promote",
    "register_partition_plan",
    "validate_next_chunk",
    "validate_claimed_partition",
    "versions_dir",
]
