"""DotMac Ticketing — a product-neutral ticket lifecycle (ADR-0006 M2).

The capability every product needs and none should own: *a durable request for
work, with one owner, a guarded lifecycle, and an auditable trail of what was
said and done.*

## The layering, which is the whole design

    lifecycle class   5, FIXED      machine semantics — SLA clock, counts-as-open
    status            9, CLOSED     what a UI calls it; which transitions are legal
    status reason     open          why it is in that status; product-declared
    tag               open          searchable only, no behaviour
    comment           —             narrative, never queried for behaviour

A product extends the **reason** layer and never the status layer. That is what
stops `dotmac_sub`'s `lastmile_rerun` — a fiber last-mile field operation —
becoming a ticket state every other product carries. Evidence for the split, and
the audit it came from, is in the starter's
`docs/inventories/ticket-sources.md`.

## Two planes, one lifecycle (ADR-0023)

The same capability genuinely runs in two security contexts, so the storage —
and only the storage — is split. `TenantTicket`/`TenantTicketComment` are
tenant-scoped with forced RLS; `PlatformTicket`/`PlatformTicketComment` are
control-plane tables with no tenant column, granted to the platform roles and
REVOKEd from `app_user`. The lifecycle, vocabulary, transition guards and reason
registry above are shared by both and know nothing about persistence.

A product data plane (ERP, Sub) uses the tenant plane; a control plane (the
vendor CP) uses the platform plane. Neither can reach the other's rows.

Each adopter installs its own copy and owns its own rows (ADR-0024). The package
is reusable code, not a fleet-wide ticket database. Cross-application ticket
data arrives through a product-local API/webhook adapter as an observation or
projection; provider names and wire mappings do not belong in this package.

## Subjects live in the product

There are no `subscriber_id` / `project_id` columns here. A ticket has many
subjects (Sub's has six, ERP's five), so they are product-owned link tables with
real foreign keys, generated by
:func:`dotmac_ticketing.linking.link_tenant_subject` or
:func:`~dotmac_ticketing.linking.link_platform_subject` — one per plane, because
a flag with a default is a plane a caller gets by forgetting to think.

## Public surface

Everything importable from this top-level namespace is stable per
`COMPATIBILITY.md`. Submodules are not: import from here.
"""

from __future__ import annotations

from dotmac_ticketing.lifecycle import (
    STANDARD_STATUSES,
    TERMINAL_CLASSES,
    Channel,
    LifecycleClass,
    Priority,
    Status,
    TransitionError,
    check_transition,
    is_open,
    sla_clock_runs,
)
from dotmac_ticketing.linking import (
    drop_subject_link,
    link_platform_subject,
    link_tenant_subject,
)
from dotmac_ticketing.manifest import module
from dotmac_ticketing.migrations import versions_dir
from dotmac_ticketing.models import (
    PLATFORM_TABLES,
    SCHEMA,
    TENANT_TABLES,
    PlatformTicket,
    PlatformTicketComment,
    TenantTicket,
    TenantTicketComment,
)
from dotmac_ticketing.vocabulary import (
    CORE_REASONS,
    ReasonSpec,
    UnknownReasonError,
    register_reasons,
    registered_reasons,
    validate_reason,
)

__version__ = "0.1.0a5"

__all__ = [
    "CORE_REASONS",
    "PLATFORM_TABLES",
    "SCHEMA",
    "STANDARD_STATUSES",
    "TENANT_TABLES",
    "TERMINAL_CLASSES",
    "Channel",
    "LifecycleClass",
    "PlatformTicket",
    "PlatformTicketComment",
    "Priority",
    "ReasonSpec",
    "Status",
    "TenantTicket",
    "TenantTicketComment",
    "TransitionError",
    "UnknownReasonError",
    "__version__",
    "check_transition",
    "drop_subject_link",
    "is_open",
    "link_platform_subject",
    "link_tenant_subject",
    "module",
    "register_reasons",
    "registered_reasons",
    "sla_clock_runs",
    "validate_reason",
    "versions_dir",
]
