"""Narrow employment-directory authority extracted from dotmac_erp."""

from dotmac_people.contracts import (
    AssignmentType,
    Conflict,
    CreateCatalogEntry,
    CreateEmployee,
    CreatePosition,
    EmployeeStatus,
    InvalidHierarchy,
    InvalidLifecycle,
    NotFound,
    PeopleError,
    PositionAssignmentCommand,
    RehireEmployee,
    ResolutionResult,
    VacancyRoutingAlert,
    VacancyRoutingPolicy,
)
from dotmac_people.manifest import module
from dotmac_people.migrations import versions_dir
from dotmac_people.models import (
    Department,
    Designation,
    Employee,
    EmploymentType,
    Position,
    PositionAssignment,
)
from dotmac_people.service import (
    assign_position,
    create_department,
    create_designation,
    create_employee,
    create_employment_type,
    create_position,
    end_assignment,
    position_is_vacant,
    rehire_employee,
    resolve_approval_chain,
    resolve_department_head,
    resolve_direct_reports,
    resolve_manager,
    search_employees,
)

__version__ = "0.1.0a1"

__all__ = [
    "AssignmentType",
    "Conflict",
    "CreateCatalogEntry",
    "CreateEmployee",
    "CreatePosition",
    "Department",
    "Designation",
    "Employee",
    "EmployeeStatus",
    "EmploymentType",
    "InvalidHierarchy",
    "InvalidLifecycle",
    "NotFound",
    "PeopleError",
    "Position",
    "PositionAssignment",
    "PositionAssignmentCommand",
    "RehireEmployee",
    "ResolutionResult",
    "VacancyRoutingAlert",
    "VacancyRoutingPolicy",
    "__version__",
    "assign_position",
    "create_department",
    "create_designation",
    "create_employee",
    "create_employment_type",
    "create_position",
    "end_assignment",
    "module",
    "position_is_vacant",
    "rehire_employee",
    "resolve_approval_chain",
    "resolve_department_head",
    "resolve_direct_reports",
    "resolve_manager",
    "search_employees",
    "versions_dir",
]
