"""Staffed inbox operations."""

from dotmac_inbox_operations.contracts import (
    AdmitToQueue,
    AssignConversation,
    AssignmentStatus,
    Conflict,
    CreateQueue,
    CreateRoutingRule,
    DispatchQueues,
    InboxOperationsError,
    PresenceState,
    PromoteFromQueue,
    QueueEligibility,
    QueueEntryStatus,
    ReleaseConversation,
    RouteConversation,
    RoutedConversation,
    SetAgentPresence,
)
from dotmac_inbox_operations.manifest import module
from dotmac_inbox_operations.migrations import versions_dir
from dotmac_inbox_operations.models import (
    ConversationAssignment,
    InboxAgentPresence,
    InboxQueue,
    InboxQueueEntry,
    InboxRoundRobinCursor,
    InboxRoutingDecision,
    InboxRoutingRule,
    InboxWorkflowEvent,
)
from dotmac_inbox_operations.service import (
    admit_to_queue,
    assign_conversation,
    cancel_queue_entry,
    create_queue,
    create_routing_rule,
    dispatch_queues_fairly,
    next_round_robin_agent,
    promote_from_queue,
    release_conversation,
    route_conversation,
    set_agent_presence,
)

__version__ = "0.1.0a3"
__all__ = [
    "AdmitToQueue",
    "AssignConversation",
    "AssignmentStatus",
    "Conflict",
    "ConversationAssignment",
    "CreateQueue",
    "CreateRoutingRule",
    "DispatchQueues",
    "InboxAgentPresence",
    "InboxOperationsError",
    "InboxQueue",
    "InboxQueueEntry",
    "InboxRoundRobinCursor",
    "InboxRoutingDecision",
    "InboxRoutingRule",
    "InboxWorkflowEvent",
    "PresenceState",
    "PromoteFromQueue",
    "QueueEligibility",
    "QueueEntryStatus",
    "ReleaseConversation",
    "RouteConversation",
    "RoutedConversation",
    "SetAgentPresence",
    "__version__",
    "admit_to_queue",
    "assign_conversation",
    "cancel_queue_entry",
    "create_queue",
    "create_routing_rule",
    "dispatch_queues_fairly",
    "module",
    "next_round_robin_agent",
    "promote_from_queue",
    "release_conversation",
    "route_conversation",
    "set_agent_presence",
    "versions_dir",
]
