"""Generic browser behaviours extracted without product decision logic."""

# Embedded JavaScript is kept readable as JavaScript rather than wrapped to the
# Python line length.
# ruff: noqa: E501

from __future__ import annotations

import json
import shutil
import subprocess

import dotmac_ui
from dotmac_ui.behaviors import (
    BEHAVIORS,
    FORM_SUBMIT,
    REPEATABLE_FIELDS,
    UNSAVED_CHANGES,
    VALIDATED_INPUT,
)


def test_behavior_contract_names_and_configuration_are_published() -> None:
    assert BEHAVIORS == (
        VALIDATED_INPUT,
        FORM_SUBMIT,
        REPEATABLE_FIELDS,
        UNSAVED_CHANGES,
    )
    assert [behavior.name for behavior in BEHAVIORS] == [
        "dmuiValidatedInput",
        "dmuiFormSubmit",
        "dmuiRepeatableFields",
        "dmuiUnsavedChanges",
    ]
    assert REPEATABLE_FIELDS.config_fields == (
        "min",
        "max",
        "initialData",
        "defaultValues",
        "fieldPrefix",
    )
    assert UNSAVED_CHANGES.config_fields == (
        "enabled",
        "message",
        "excludeFields",
        "captureDelay",
    )


def test_behavior_asset_is_manifested_cache_busted_and_domain_free() -> None:
    source = dotmac_ui.behavior_script_path().read_text(encoding="utf-8")
    manifest_assets = {
        asset["path"]: asset for asset in dotmac_ui.asset_manifest()["assets"]
    }

    assert dotmac_ui.BEHAVIOR_SCRIPT_RELPATH in manifest_assets
    assert dotmac_ui.behavior_script_url().startswith(
        f"/static/{dotmac_ui.BEHAVIOR_SCRIPT_RELPATH}?v="
    )
    assert dotmac_ui.asset_digest(dotmac_ui.BEHAVIOR_SCRIPT_RELPATH) in (
        dotmac_ui.behavior_script_url()
    )
    assert "Generated by dotmac-ui" in source
    for product_policy in (
        "invoiceLineItems",
        "contactRows",
        "formatCurrency",
        "parseCurrency",
        "taxRates",
        "isPrimary",
        "NGN",
        "countryCode",
    ):
        assert product_policy not in source


def test_behavior_asset_executes_generic_validation_repeatable_and_cleanup_canaries(
    tmp_path,
) -> None:
    """Exercise state, boundary events, and stable listener cleanup in Node.

    This uses only Node's standard runtime: no npm dependency or simulated
    browser library is part of the package contract.
    """

    asset = json.dumps(str(dotmac_ui.behavior_script_path()))
    probe = tmp_path / "behavior-probe.cjs"
    probe.write_text(
        f"""
const assert = require('node:assert/strict');
const emitted = [];
global.window = {{
  addEventListener(name, handler) {{ emitted.push(['window-add', name, handler]); }},
  removeEventListener(name, handler) {{ emitted.push(['window-remove', name, handler]); }},
  dispatchEvent(event) {{ emitted.push(['window-event', event.type, event.detail]); }},
  confirm() {{ return false; }},
}};
global.document = {{
  addEventListener(name, handler) {{ emitted.push(['document-add', name, handler]); }},
  removeEventListener(name, handler) {{ emitted.push(['document-remove', name, handler]); }},
  getElementById() {{ return null; }},
}};
global.CustomEvent = class CustomEvent {{
  constructor(type, options = {{}}) {{ this.type = type; this.detail = options.detail; }}
}};
const api = require({asset});

const registered = [];
global.Alpine = {{
  data(name, factory) {{
    registered.push(name);
    assert.equal(typeof factory, 'function');
  }},
}};
const alpineInit = emitted.find(entry => entry[0] === 'document-add' && entry[1] === 'alpine:init');
assert.ok(alpineInit, 'browser asset did not install its Alpine registration hook');
alpineInit[2]();
assert.deepEqual(registered, [
  'dmuiValidatedInput',
  'dmuiFormSubmit',
  'dmuiRepeatableFields',
  'dmuiUnsavedChanges',
]);

const repeatable = api.createRepeatableFields({{
  min: 0,
  max: 2,
  initialData: [{{name: 'first'}}],
  defaultValues: {{enabled: true}},
  fieldPrefix: 'contact',
}});
repeatable.init();
assert.equal(repeatable.items.length, 1);
assert.deepEqual(repeatable.items[0], {{id: 1, enabled: true, name: 'first'}});
repeatable.addItem({{name: 'second'}});
repeatable.addItem({{name: 'third'}});
assert.equal(repeatable.items.length, 2);
assert.equal(emitted.at(-1)[1], 'dmui:repeatable-limit');
repeatable.moveUp(1);
assert.equal(repeatable.items[0].name, 'second');
assert.deepEqual(JSON.parse(repeatable.toJSON()), [
  {{enabled: true, name: 'second'}},
  {{enabled: true, name: 'first'}},
]);

const validated = api.createValidatedInput({{
  name: 'email',
  initialValue: 'not-an-email',
  rules: 'required|email',
}});
validated.init();
assert.equal(validated.validateClient(), 'Please enter a valid email address');
validated.value = 'owner@example.com';
assert.equal(validated.validateClient(), null);

const elementListeners = [];
const fields = [
  {{name: 'title', type: 'text', value: 'Draft', checked: false}},
  {{name: 'tags', type: 'checkbox', value: 'urgent', checked: true}},
  {{name: 'tags', type: 'checkbox', value: 'customer', checked: false}},
];
const unsaved = api.createUnsavedChanges({{captureDelay: 0}});
unsaved.$el = {{
  addEventListener(name, handler) {{ elementListeners.push(['add', name, handler]); }},
  removeEventListener(name, handler) {{ elementListeners.push(['remove', name, handler]); }},
  querySelectorAll() {{ return fields; }},
}};
unsaved.$nextTick = callback => callback();
unsaved.init();
setTimeout(() => {{
  fields[0].value = 'Changed';
  unsaved.checkForChanges();
  assert.equal(unsaved.isDirty, true);
  const before = unsaved._beforeUnloadHandler;
  const click = unsaved._linkClickHandler;
  unsaved.destroy();
  assert.ok(emitted.some(entry => entry[0] === 'window-remove' && entry[2] === before));
  assert.ok(emitted.some(entry => entry[0] === 'document-remove' && entry[2] === click));
  process.stdout.write('ok');
}}, 5);
""",
        encoding="utf-8",
    )

    node = shutil.which("node")
    assert node, "Node is required for the dependency-free browser behavior probe"
    completed = subprocess.run(  # noqa: S603
        [node, str(probe)],
        check=True,
        capture_output=True,
        text=True,
    )

    assert completed.stdout == "ok"
